import 'package:test/test.dart';
import 'package:wardrobe_core/wardrobe_core.dart';

void main() {
  final captured = DateTime.utc(2026, 8, 5);

  ItemPhoto photo({
    required String uri,
    PhotoRole role = PhotoRole.front,
    String? cutoutUri,
    bool isPrimary = false,
  }) =>
      ItemPhoto(
        uri: uri,
        role: role,
        capturedAt: captured,
        cutoutUri: cutoutUri,
        isPrimary: isPrimary,
      );

  group('cutouts', () {
    test('a photo without one renders itself', () {
      final plain = photo(uri: 'file:///front.jpg');
      expect(plain.hasCutout, isFalse);
      expect(plain.displayUri, 'file:///front.jpg');
    });

    test('a photo with one renders the cutout', () {
      final cut = photo(
        uri: 'file:///front.jpg',
        cutoutUri: 'file:///front-cutout.png',
      );
      expect(cut.hasCutout, isTrue);
      expect(cut.displayUri, 'file:///front-cutout.png');
    });

    test('a cutout can be attached after the fact', () {
      // It is derived, so it arrives later than the photo and may be
      // regenerated by a better remover without the original changing.
      final set = PhotoSet([photo(uri: 'file:///front.jpg')])
          .withCutout('file:///front.jpg', 'file:///cut.png');

      expect(set.photos.single.cutoutUri, 'file:///cut.png');
      expect(set.photos.single.uri, 'file:///front.jpg');
    });

    test('attaching one for a photo that is gone changes nothing', () {
      // A cutout arriving for something the user has since deleted is not an
      // error worth raising at them.
      final set = PhotoSet([photo(uri: 'file:///front.jpg')])
          .withCutout('file:///deleted.jpg', 'file:///cut.png');

      expect(set.photos.single.cutoutUri, isNull);
    });

    test('survives a JSON round trip', () {
      final original = PhotoSet([
        photo(uri: 'file:///a.jpg', cutoutUri: 'file:///a-cut.png'),
        photo(uri: 'file:///b.jpg', role: PhotoRole.careTag),
      ]);

      expect(PhotoSet.fromJson(original.toJson()), original);
    });

    test('an absent cutout is absent from the JSON, not null', () {
      // Same discipline as the care model: a key that is present but null
      // invites a reader to treat it as a stated value.
      final json = photo(uri: 'file:///a.jpg').toJson();
      expect(json.containsKey('cutoutUri'), isFalse);
    });
  });

  group('which photo a list shows', () {
    test('an explicit primary wins outright', () {
      // The user said so, and that outranks any heuristic.
      final set = PhotoSet([
        photo(uri: 'file:///front.jpg', cutoutUri: 'file:///cut.png'),
        photo(uri: 'file:///worn.jpg', role: PhotoRole.worn, isPrimary: true),
      ]);

      expect(set.displayPhoto?.uri, 'file:///worn.jpg');
    });

    test('a front shot with a cutout beats one without', () {
      // The whole point of the feature: a list of garments on transparency is
      // scannable, and a list of garments on assorted duvets is not.
      final set = PhotoSet([
        photo(uri: 'file:///plain.jpg'),
        photo(uri: 'file:///cut-source.jpg', cutoutUri: 'file:///cut.png'),
      ]);

      expect(set.displayPhoto?.uri, 'file:///cut-source.jpg');
      expect(set.displayImageUri, 'file:///cut.png');
    });

    test('a cutout of any role beats a front shot without one', () {
      final set = PhotoSet([
        photo(uri: 'file:///front.jpg'),
        photo(
          uri: 'file:///detail.jpg',
          role: PhotoRole.detail,
          cutoutUri: 'file:///detail-cut.png',
        ),
      ]);

      expect(set.displayImageUri, 'file:///detail-cut.png');
    });

    test('falls back to a front shot when nothing has a cutout', () {
      final set = PhotoSet([
        photo(uri: 'file:///tag.jpg', role: PhotoRole.careTag),
        photo(uri: 'file:///front.jpg'),
      ]);

      expect(set.displayImageUri, 'file:///front.jpg');
    });

    test('an empty set has nothing to show', () {
      expect(PhotoSet.empty.displayPhoto, isNull);
      expect(PhotoSet.empty.displayImageUri, isNull);
    });
  });

  group('choosing which photo is shown', () {
    ItemPhoto shot(String uri, {String? cutout, bool primary = false}) =>
        ItemPhoto(
          uri: uri,
          cutoutUri: cutout,
          role: PhotoRole.front,
          capturedAt: DateTime.utc(2026, 1, 1),
          isPrimary: primary,
        );

    test('a retaken photo can be promoted over one that has a cutout', () {
      // The case this exists for. `displayPhoto` prefers whichever photo has a
      // cutout, which is right until the cutout is the reason the user took
      // another picture — without a way to say "show this one" they would keep
      // seeing the bad mask.
      final set = PhotoSet([shot('old', cutout: 'old-cut'), shot('new')]);
      expect(set.displayPhoto!.uri, 'old');

      expect(set.withPrimary('new').displayPhoto!.uri, 'new');
    });

    test('promoting one demotes the other', () {
      final set = PhotoSet([shot('a', primary: true), shot('b')]);

      final promoted = set.withPrimary('b');

      expect(
          promoted.photos.where((p) => p.isPrimary).map((p) => p.uri), ['b']);
    });

    test('the old photo is kept, not replaced', () {
      // Sync unions photos by URI and would re-add anything deleted on the
      // next round trip, so a retake adds and promotes rather than removing.
      final set = PhotoSet([shot('old', cutout: 'old-cut')]);

      final after = set.add(shot('new')).withPrimary('new');

      expect(after.length, 2);
      expect(after.photos.first.cutoutUri, 'old-cut');
    });

    test('promoting a photo that is not there changes nothing', () {
      final set = PhotoSet([shot('a')]);

      expect(set.withPrimary('missing'), same(set));
    });
  });
}
